config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-UserProfile:
      branch: master
      repo: https://github.com/athenarc/EOSCF-UserProfile
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-UserProfile git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-brass-quokka.sh
        container: qc.acc_gummy-chartreuse-chinchilla
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-UserProfile find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-saffron-ragdoll.sh
        container: qc.doc_flabby-teal-ladybird
      github.com/athenarc/EOSCF-UserProfile git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cobalt-eagle.sh
        container: qc.doc_lanky-ecru-octopus
      github.com/athenarc/EOSCF-UserProfile markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-wisteria-bison.sh
        container: qc.doc_crappy-puce-collie
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-UserProfile licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-malachite-macaque.sh
        container: qc.lic_whiny-platinum-bobcat
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-UserProfile bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-wisteria-tapir.sh
        container: qc.sec_blurry-eggplant-chameleon
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-UserProfile flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-charcoal-tuatara.sh
        container: qc.sty_ready-white-bat
      github.com/athenarc/EOSCF-UserProfile hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-tangerine-penguin.sh
        container: qc.sty_skinny-taupe-stingray
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-UserProfile get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-silver-lemur.sh
        container: qc.ver_freaky-azure-wolverine
timeout: 5400
